### ISSUE TITLE
missing MemberExpression

### ISSUE THREAD

**Issue by kariae** [kyldvs/ast-types-flow#1]
For Node of type `AssignmentExpression`, the `left` property is a `Pattern` and the Pattern type miss `MemberExpression` type, [here](https://astexplorer.net/#/gist/2f909f8f9668cecb5448f62b9d02d114/37dd67ae3fc4921e424f3babb59cb7098b0973d6) is an example.

**Comment by kyldvs** [comment]
Thanks for the issue, but this is a really old project that likely has a lot of deviations from the current types. This project should be considered unmaintained at this point so I'm going to close this out.
