### ISSUE TITLE
Missing license files

### ISSUE THREAD

**Issue by dariagrudzien** [kyldvs/ast-types-flow#2]
@kyldvs Hi Kyle, thank you for this package. Would you mind adding the license file to the repo & the npm package? Without it we're not really able to use it, because it makes the npm package a distribution of proprietary code.

Many thanks.

**Comment by kyldvs** [comment]
I'm curious what you intend to use this for? The package is basically unmaintained. I haven't updated the types in 3 years and I believe they have changed significantly in that time.

**Comment by kyldvs** [comment]
Either way, I added an MIT license just now

**Comment by dariagrudzien** [comment]
@kyldvs Thanks, Kyle! Your package is used by `eslint-plugin-jsx-a11y@6.1.2` on which we depend on :) Any chance you'd be able to add the license file to the npm package v0.0.7?

**Comment by ajkl2533** [comment]
@kyldvs could you please release v0.0.8 which contains license file, that's all we actually need :)

**Comment by kyldvs** [comment]
https://www.npmjs.com/package/ast-types-flow/v/0.0.8 is marked as MIT so I think this is resolved now
